// Generated by scripts/build.ts from the bundled module worker.
export const bundledWorker = {
  "engineBuildId": "spice-ts-js-e7df0b4339f325a5",
  "sha256": "e7df0b4339f325a53108ac307d2f53ce7549c0bd4e539a889b4b7fca61edb02d",
  "numericEngineBuildId": "spice-ts-wasm-d034ba96f6fc6c18",
  "numericSha256": "d034ba96f6fc6c183020f3b15a86557b1b68e37ba7e2c97619beeb693ab33cfd",
  "numericByteLength": 3506
} as const;
