// Generated by scripts/build.ts from the bundled module worker.
export const bundledWorker = {
  "engineBuildId": "spice-ts-js-eb8e34837be477ba",
  "sha256": "eb8e34837be477ba8f625862139b94b379ef2e9d58cdedf09eaee26a7a5f13bf",
  "numericEngineBuildId": "spice-ts-wasm-5d574b2b44f02e1e",
  "numericSha256": "5d574b2b44f02e1e9b4f79351eaf2eaad75d2fd4c56ad7fd4a08ec515de4d76a",
  "numericByteLength": 2900
} as const;
