// Generated by scripts/build.ts from the bundled module worker.
export const bundledWorker = {
  "engineBuildId": "spice-ts-js-6fdb340d5eda1ea6",
  "sha256": "6fdb340d5eda1ea6a9732bf20a8f352104cd2c8ce32e9705bec8b211b36d5bfb",
  "numericEngineBuildId": "spice-ts-wasm-d034ba96f6fc6c18",
  "numericSha256": "d034ba96f6fc6c183020f3b15a86557b1b68e37ba7e2c97619beeb693ab33cfd",
  "numericByteLength": 3506
} as const;
