import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { build } from 'tsup';

const directory = new URL('../dist/', import.meta.url);
await rm(directory, { recursive: true, force: true });
await mkdir(directory, { recursive: true });

await build({
  entry: { worker: 'src/worker.ts' },
  format: ['esm'],
  platform: 'neutral',
  bundle: true,
  splitting: false,
  sourcemap: true,
  clean: false,
  dts: false,
  noExternal: ['@spice-ts/core', '@spice-ts/protocol'],
  external: ['node:worker_threads', 'worker_threads', 'url', 'eecircuit-engine'],
});

const worker = await readFile(new URL('worker.js', directory));
const sha256 = createHash('sha256').update(worker).digest('hex');
const engineBuildId = `spice-ts-js-${sha256.slice(0, 16)}`;
const manifest = {
  schemaVersion: 1,
  engineBuildId,
  worker: { url: './worker.js', sha256 },
};
await writeFile(new URL('manifest.json', directory), `${JSON.stringify(manifest, null, 2)}\n`);
await writeFile(new URL('../src/build-manifest.ts', import.meta.url), `// Generated by scripts/build.ts from the bundled module worker.\nexport const bundledWorker = ${JSON.stringify({ engineBuildId, sha256 }, null, 2)} as const;\n`);

await build({
  entry: { index: 'src/index.ts' },
  format: ['esm'],
  platform: 'neutral',
  bundle: true,
  splitting: false,
  sourcemap: true,
  clean: false,
  dts: { compilerOptions: { composite: false } },
  noExternal: ['@spice-ts/protocol'],
  external: ['node:fs/promises', 'node:worker_threads'],
});
